# Generated by Django 4.1.2 on 2023-01-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0001_initial")]

    operations = [migrations.DeleteModel(name="BannerImage"), migrations.DeleteModel(name="Offer")]
