# Generated by Django 4.1.2 on 2022-12-29 22:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0001_initial")]

    operations = [
        migrations.AlterField(model_name="brand", name="name", field=models.CharField(default="", max_length=100)),
        migrations.AlterField(model_name="brandmodel", name="name", field=models.CharField(default="", max_length=100)),
        migrations.AlterField(model_name="cutomerprofile", name="auth_token", field=models.CharField(blank=True, default="", max_length=100)),
        migrations.AlterField(model_name="cutomerprofile", name="forget_password_token", field=models.CharField(blank=True, default="", max_length=100)),
        migrations.AlterField(model_name="cutomerregistration", name="name", field=models.CharField(blank=True, default="", max_length=50)),
        migrations.AlterField(model_name="cutomerregistration", name="password", field=models.CharField(default="", max_length=20)),
        migrations.AlterField(model_name="franchise", name="address", field=models.CharField(default="", max_length=500)),
        migrations.AlterField(model_name="franchise", name="franchise_id", field=models.CharField(default="", max_length=20)),
        migrations.AlterField(model_name="franchise", name="name", field=models.CharField(default="", max_length=40)),
        migrations.AlterField(model_name="franchise", name="phone", field=models.CharField(blank=True, default="", max_length=15)),
        migrations.AlterField(model_name="modelspecifications", name="color", field=models.CharField(default="", max_length=30)),
        migrations.AlterField(model_name="modelspecifications", name="internal_storage", field=models.CharField(default="", max_length=30)),
        migrations.AlterField(model_name="pickupboy", name="address", field=models.CharField(default="", max_length=500)),
        migrations.AlterField(model_name="pickupboy", name="name", field=models.CharField(default="", max_length=40)),
        migrations.AlterField(model_name="pickupboy", name="phone", field=models.CharField(default="", max_length=15)),
        migrations.AlterField(model_name="pickupboy", name="pickup_id", field=models.CharField(default="", max_length=20)),
        migrations.AlterField(model_name="pickupboy", name="place", field=models.CharField(default="", max_length=40)),
        migrations.AlterField(model_name="questionoption", name="image_description", field=models.CharField(default="", max_length=500)),
        migrations.AlterField(model_name="questions", name="questions", field=models.CharField(default="", max_length=500)),
    ]
