# Generated by Django 4.1.2 on 2023-01-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0001_initial")]

    operations = [migrations.RenameField(model_name="userreply", old_name="user_question_answer", new_name="user_request")]
