# Generated by Django 4.1.2 on 2023-01-25 01:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="request_id",
            field=models.CharField(default="048CE3C7", editable=False, max_length=100),
        )
    ]
