# Generated by Django 4.1.2 on 2023-01-28 23:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="brandmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("laptop", "Laptop"),
                    ("tablet", "Tablet"),
                    ("accessories", "Accessories"),
                    ("camera", "Camera"),
                    ("earbud", "Earbud"),
                    ("headphone", "Headphone"),
                    ("smartwatch", "Smartwatch"),
                    ("smartband", "Smartband"),
                ],
                default="mobile",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="back_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/BackImage", verbose_name="back side of the phone"
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="bottom_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/BottomSide", verbose_name="bottom side of the phone"
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="front_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/FrontImage", verbose_name="front side of the phone"
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="left_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/LeftSide", verbose_name="left side of the phone"
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="right_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/RightSide", verbose_name="right side of the phone"
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="selfie_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/Selfie", verbose_name="Selfie with Customer"
            ),
        ),
        migrations.AlterField(
            model_name="pickupdata",
            name="top_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pickup/TopSide", verbose_name="top side of the phone"
            ),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="question_images"),
        ),
    ]
