# Generated by Django 4.1.2 on 2023-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0002_rename_user_question_answer_userreply_user_request")]

    operations = [migrations.AddField(model_name="userrequest", name="is_submitted", field=models.BooleanField(default=False))]
