# Generated by Django 4.1.2 on 2023-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0002_delete_bannerimage_delete_offer")]

    operations = [
        migrations.AddField(
            model_name="brand", name="slug", field=models.SlugField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(model_name="brand", name="name", field=models.CharField(max_length=100)),
        migrations.AlterField(model_name="brandmodel", name="name", field=models.CharField(max_length=100)),
        migrations.AlterField(model_name="modelspecifications", name="color", field=models.CharField(max_length=30)),
    ]
