# Generated by Django 4.1.2 on 2022-12-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0002_alter_brand_name_alter_brandmodel_name_and_more")]

    operations = [
        migrations.RenameModel(old_name="CutomerProfile", new_name="CustomerProfile"),
        migrations.RenameModel(old_name="CutomerRegistration", new_name="CustomerRegistration"),
    ]
