# Generated by Django 4.1.2 on 2023-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0002_brandmodel_category_alter_pickupdata_back_image_and_more")]

    operations = [
        migrations.AlterField(
            model_name="brand", name="image", field=models.FileField(blank=True, null=True, upload_to="Brand")
        )
    ]
