# Generated by Django 4.1.2 on 2023-01-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0002_alter_userrequest_request_id")]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="request_id",
            field=models.CharField(default="CB867EE7", editable=False, max_length=100),
        )
    ]
