# Generated by Django 4.1.2 on 2022-12-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0003_rename_cutomerprofile_customerprofile_and_more")]

    operations = [migrations.DeleteModel(name="Card")]
