# Generated by Django 4.1.2 on 2023-01-24 10:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0003_brand_slug_alter_brand_name_alter_brandmodel_name_and_more")]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerprofile", name="auth_token", field=models.CharField(blank=True, max_length=100)
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="forget_password_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customerregistration", name="name", field=models.CharField(blank=True, max_length=50)
        ),
        migrations.AlterField(
            model_name="customerregistration", name="password", field=models.CharField(max_length=20)
        ),
        migrations.AlterField(model_name="franchise", name="address", field=models.CharField(max_length=500)),
        migrations.AlterField(model_name="franchise", name="franchise_id", field=models.CharField(max_length=20)),
        migrations.AlterField(model_name="franchise", name="name", field=models.CharField(max_length=40)),
        migrations.AlterField(model_name="franchise", name="phone", field=models.CharField(blank=True, max_length=15)),
        migrations.AlterField(
            model_name="modelspecifications", name="internal_storage", field=models.CharField(max_length=30)
        ),
        migrations.AlterField(model_name="pickupboy", name="address", field=models.CharField(max_length=500)),
        migrations.AlterField(model_name="pickupboy", name="name", field=models.CharField(max_length=40)),
        migrations.AlterField(model_name="pickupboy", name="phone", field=models.CharField(max_length=15)),
        migrations.AlterField(model_name="pickupboy", name="pickup_id", field=models.CharField(max_length=20)),
        migrations.AlterField(model_name="pickupboy", name="place", field=models.CharField(max_length=40)),
        migrations.AlterField(model_name="questionoption", name="text", field=models.CharField(max_length=500)),
    ]
