# Generated by Django 4.1.2 on 2023-01-25 01:18

from django.db import migrations, models
import official.models


class Migration(migrations.Migration):

    dependencies = [("official", "0003_alter_userrequest_request_id")]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="request_id",
            field=models.CharField(default=official.models.UserRequest.get_request_id, editable=False, max_length=100),
        )
    ]
