# Generated by Django 4.1.2 on 2022-12-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0004_delete_card")]

    operations = [migrations.RenameField(model_name="questions", old_name="model_question", new_name="brand_model")]
