# Generated by Django 4.1.2 on 2023-01-24 16:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0004_alter_brand_slug_alter_customerprofile_auth_token_and_more")]

    operations = [
        migrations.AddField(
            model_name="brandmodel",
            name="slug",
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brandmodel",
            name="image",
            field=models.FileField(default=1, upload_to="models/"),
            preserve_default=False,
        ),
    ]
