# Generated by Django 4.1.2 on 2023-01-24 19:09

import official.models

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0006_alter_brandmodel_slug")]

    operations = [
        migrations.RenameModel(old_name="ModelSpecifications", new_name="Variant"),
        migrations.AlterField(
            model_name="brandmodel",
            name="image",
            field=models.FileField(upload_to=official.models.BrandModel.get_image_path),
        ),
    ]
