# Generated by Django 4.1.2 on 2023-01-25 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("official", "0006_userrequest_is_franchise_accepted")]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="pickupboy",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="official.pickupboy"
            ),
        )
    ]
