# Generated by Django 4.1.2 on 2023-01-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0007_userrequest_pickupboy")]

    operations = [
        migrations.RemoveField(model_name="adminwallet", name="franchise"),
        migrations.RenameField(model_name="franchisewallet", old_name="last_paid_amount", new_name="amount"),
        migrations.RemoveField(model_name="franchisewallet", name="wallet_amount"),
        migrations.DeleteModel(name="AdminSendRecord"),
        migrations.DeleteModel(name="AdminWallet"),
    ]
