# Generated by Django 4.1.2 on 2023-01-24 19:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0007_rename_modelspecifications_variant_and_more")]

    operations = [
        migrations.RemoveField(model_name="variant", name="price"),
        migrations.AddField(
            model_name="variant", name="max_price", field=models.FloatField(default=10000), preserve_default=False
        ),
        migrations.AddField(
            model_name="variant", name="min_price", field=models.FloatField(default=1000), preserve_default=False
        ),
    ]
