# Generated by Django 4.1.2 on 2023-01-25 11:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0008_remove_adminwallet_franchise_and_more")]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Address of person who will deliver the product"
            ),
        ),
        migrations.AddField(
            model_name="userrequest", name="city", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AddField(
            model_name="userrequest",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name of person who will deliver the product"
            ),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Contact number of person who will deliver the product",
            ),
        ),
        migrations.AddField(
            model_name="userrequest", name="pincode", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AddField(
            model_name="userrequest",
            name="prefferred_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
