# Generated by Django 4.1.2 on 2023-01-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0009_remove_variant_year_alter_variant_max_price_and_more")]

    operations = [
        migrations.AlterModelOptions(name="variant", options={}),
        migrations.AddField(
            model_name="userrequest", name="request_id", field=models.CharField(default="4C6960BF", max_length=100)
        ),
    ]
