# Generated by Django 4.1.2 on 2023-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0009_userrequest_address_userrequest_city_and_more")]

    operations = [
        migrations.AddField(
            model_name="franchisewallet",
            name="type",
            field=models.CharField(
                choices=[("to_franchise", "to_franchise"), ("to_admin", "to_admin")],
                default="to_franchise",
                max_length=100,
            ),
        )
    ]
