# Generated by Django 4.1.2 on 2023-01-25 20:04

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0010_franchisewallet_type")]

    operations = [
        migrations.CreateModel(
            name="PickupData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("complete", "complete"),
                            ("requote", "requote"),
                            ("fail", "fail"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("imei_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "front_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Front Image", verbose_name="front side of the phone"
                    ),
                ),
                (
                    "back_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Back Image", verbose_name="back side of the phone"
                    ),
                ),
                (
                    "top_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Top Side", verbose_name="top side of the phone"
                    ),
                ),
                (
                    "bottom_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Bottom Side", verbose_name="bottom side of the phone"
                    ),
                ),
                (
                    "right_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Right Side", verbose_name="right side of the phone"
                    ),
                ),
                (
                    "left_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="Left Side", verbose_name="left side of the phone"
                    ),
                ),
                (
                    "user_request",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="official.userrequest"),
                ),
            ],
        )
    ]
