# Generated by Django 4.1.2 on 2023-01-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0011_alter_userrequest_request_id")]

    operations = [
        migrations.AlterField(
            model_name="userrequest", name="request_id", field=models.CharField(default="BB3704DD", max_length=100)
        )
    ]
