# Generated by Django 4.1.2 on 2023-01-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("official", "0012_pickupdata_selfie")]

    operations = [migrations.RenameField(model_name="pickupdata", old_name="selfie", new_name="selfie_image")]
