# Generated by Django 4.1.2 on 2023-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0012_alter_userrequest_request_id")]

    operations = [
        migrations.AlterField(
            model_name="userrequest", name="request_id", field=models.CharField(default="<FUNCTIO", max_length=100)
        )
    ]
