# Generated by Django 4.1.2 on 2023-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("official", "0013_alter_userrequest_request_id")]

    operations = [
        migrations.AddField(model_name="userrequest", name="is_quoted", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="userrequest",
            name="request_id",
            field=models.CharField(default="<FUNCTIO", editable=False, max_length=100),
        ),
    ]
