# Generated by Django 4.1.2 on 2023-01-25 22:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0013_rename_selfie_pickupdata_selfie_image")]

    operations = [
        migrations.AddField(model_name="pickupdata", name="remarks", field=models.TextField(blank=True, null=True))
    ]
