# Generated by Django 4.1.2 on 2023-01-25 22:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("official", "0014_pickupdata_remarks")]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("complete", "complete"), ("requote", "requote"), ("fail", "fail")],
                default="pending",
                max_length=100,
            ),
        )
    ]
