from . import views
from django.urls import path


app_name = "official"

urlpatterns = [
    path("loginpage/", views.loginPage, name="loginpage"),
    path("forgotpassword/", views.forgotPassword, name="forgotpassword"),
    path("", views.home, name="home"),
    path("franchise/", views.franchise, name="franchise"),
    path("franchisedetails/<int:id>/", views.viewFranchiseDetails, name="franchisedetails"),
    path("pickupboylist/<int:id>/", views.pickUpBoyList, name="pickupboylist"),
    path("deletefranchise/<int:id>/", views.delete_franchise, name="deletefranchise"),
    path("editfranchise/<int:id>/", views.EditFranchise, name="editfranchise"),
    path("getprofiledata/<int:id>/", views.getprofiledata, name="getprofiledata"),
    path("editform/<int:id>/", views.editform, name="editform"),
    path("brand/", views.brand, name="brand"),
    path("editbrand/<int:id>/", views.edit_brand, name="editbrand"),
    path("getbranddata/<int:id>/", views.getbranddata, name="getbranddata"),
    path("deletebrand/<int:id>/", views.delete_brand, name="deletebrand"),
    path("model/<int:id>/", views.Model, name="model"),
    path("getmodeldata/<int:id>/", views.get_model_data, name="getmodeldata"),
    path("editmodel/<int:id>/", views.editModel, name="editmodel"),
    path("modelspecification/<int:id>/", views.model_specification, name="modelspecification"),
    path("questions/", views.questions, name="questions"),
    path("questionsadding/", views.question_adding, name="questionsadding"),
    path("questionsave/", views.questsave, name="questionsave"),
    path("sub_qs_adding/", views.subquestionFirst, name="sub_qs_adding"),
    path("sub_qs_adding_page/<str:id>/", views.subquestion_page, name="sub_qs_adding_page"),
    path("deductionsettings/", views.deduction_settings, name="deductionsettings"),
    path("questionfordeduction/<str:id>/", views.question_for_deduction, name="questionfordeduction"),
    path("questionid/", views.questionId, name="questionid"),
    path("userrequestlist/", views.userRequestList, name="userrequestlist"),
    path("userdetails/", views.userDetails, name="userdetails"),
    path("wallet/", views.wallet, name="wallet"),
    path("viewpayment/<int:id>/", views.viewPayment, name="viewpayment"),
    path("savepayment/<int:id>/", views.save_payment, name="savepayment"),
    path("franchisewallet/", views.franchise_wallet, name="franchisewallet"),
    path("transactionhistory/", views.transactionHistory, name="transactionhistory"),
    path("test/", views.test, name="test"),
    path("profile/", views.profile, name="profile"),
    path("logout_view/", views.logout_view, name="logout_view"),
    path("settings/", views.settings, name="settings"),
    path("offers/", views.offers, name="offers"),
    path("delete_banner/<int:id>/", views.delete_banner, name="delete_banner"),
    path("delete_offer/<int:id>/", views.delete_offer, name="delete_offer"),
]
