# Generated by Django 4.1.2 on 2023-01-24 10:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city_name", models.CharField(max_length=100)),
            ],
        )
    ]
