# Generated by Django 4.1.2 on 2023-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="city",
            name="icon",
            field=models.ImageField(default=1, upload_to="city_icons"),
            preserve_default=False,
        )
    ]
