# Generated by Django 4.1.2 on 2023-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0002_city_icon")]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("banner", models.FileField(blank=True, null=True, upload_to="gallery/")),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("offer", models.FileField(blank=True, null=True, upload_to="gallery/")),
            ],
        ),
        migrations.AlterModelOptions(name="city", options={"verbose_name": "City", "verbose_name_plural": "Cities"}),
    ]
