# Generated by Django 4.1.2 on 2023-01-24 10:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0003_bannerimage_offer_alter_city_options")]

    operations = [
        migrations.AlterField(
            model_name="bannerimage", name="banner", field=models.FileField(blank=True, null=True, upload_to="banners/")
        ),
        migrations.AlterField(
            model_name="offer", name="offer", field=models.FileField(blank=True, null=True, upload_to="offers/")
        ),
    ]
