# Generated by Django 4.1.2 on 2023-01-24 13:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0004_alter_bannerimage_banner_alter_offer_offer")]

    operations = [
        migrations.RenameField(model_name="bannerimage", old_name="banner", new_name="image"),
        migrations.AddField(
            model_name="bannerimage",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
