# Generated by Django 4.1.2 on 2023-01-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_rename_banner_bannerimage_image_bannerimage_name")]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(blank=True, null=True, upload_to="team/")),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        )
    ]
