# Generated by Django 4.1.2 on 2023-01-24 13:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0006_team")]

    operations = [
        migrations.AlterField(
            model_name="bannerimage",
            name="image",
            field=models.FileField(default=1, upload_to="banners/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer",
            field=models.FileField(default=1, upload_to="offers/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.FileField(default=1, upload_to="team/"),
            preserve_default=False,
        ),
    ]
